version: 1.1.{build}
image: Visual Studio 2017
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - ExpressionToString/
    - ExpressionTreeVisualizer/
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
configuration: Release
artifacts:
  - path: ExpressionToString\bin\Release\netstandard2.0\*.nupkg
    type: NuGetPackage
  - path: /ExpressionTreeVisualizer\bin\Release\.*.dll/, 
    name: visualizer
    type: File
  - path: ExpressionTreeVisualizer\bin\Release\*.pdb
    name: visualizer_pdb
    type: File
deploy:
  - provider: NuGet
    api_key:
      secure: ggnvR8rEMLbVOYOAMBXmjD+ohPaPoCcMwwEPdQvMbpjt+HEHWFxZYNGXs+O1x8tD
    artifact: /.*\.nupkg/
  - provider: GitHub
    desciprion: ''
    auth_token:
      secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
    artifact: visualizer, visualizer_pdb
matrix:
  fast_finish: true